INSERT INTO `puzzles` (`id`, `puzzle`, `answer`, `difficulty`) values
('1', 'w-K-b6, w-R-b7, b-K-a8, b-N-a6', '1.Rd7 Nb4 2.Rd8', 1072),
('2', 'w-K-f6, w-Q-f1, b-K-h8, b-B-h7, b-p-g6', '1.Qa8 g5 2.Kf7', 784),
('3', 'w-K-f6, w-Q-f1, b-K-h8, b-B-h7, b-p-g6', '1.Qa8 g5 2.Kf7', 1151),
('4', 'w-K-f6, w-Q-f1, b-K-h8, b-B-h7, b-p-g6', '1.Qa8 g5 2.Kf7', 1146),
('5', 'w-K-f6, w-Q-f1, b-K-h8, b-B-h7, b-p-g6', '1.Qa8 g5 2.Kf7', 1336),
('6', 'w-K-f6, w-Q-f1, b-K-h8, b-B-h7, b-p-g6', '1.Qa8 g5 2.Kf7', 1336),
('7', 'w-K-f6, w-Q-f1, b-K-h8, b-B-h7, b-p-g6', '1.Qa8 g5 2.Kf7', 1972),
('8', 'w-K-f6, w-Q-f1, b-K-h8, b-B-h7, b-p-g6', '1.Qa8 g5 2.Kf7', 1620),
('9', 'w-K-f6, w-Q-f1, b-K-h8, b-B-h7, b-p-g6', '1.Qa8 g5 2.Kf7', 1027),
('10', 'w-K-f6, w-Q-f1, b-K-h8, b-B-h7, b-p-g6', '1.Qa8 g5 2.Kf7', 1394),
('11', '', 'Quis reiciendis ab velit cum adipisci.', 1552),
('12', '', 'Pariatur dolorem porro aut quo aut reiciendis et.', 1216),
('13', '', 'Recusandae ut aspernatur ea ut ratione quo.', 1574),
('14', '', 'Possimus at dignissimos ut temporibus autem est blanditiis.', 1865),
('15', '', 'Non et est ut recusandae possimus esse qui.', 1157),
('16', '', 'Voluptatem ut quas pariatur perferendis.', 1104),
('17', '', 'Iure nam inventore expedita sint voluptatem et.', 1718),
('18', '', 'Accusamus tempore recusandae quo numquam aut.', 780),
('19', '', 'Repellendus temporibus totam neque tempore.', 641),
('20', '', 'Nisi deleniti fugiat et eius voluptatibus debitis.', 559),
('21', '', 'Cum voluptatibus necessitatibus soluta nam aperiam.', 1153),
('22', '', 'At quis voluptas enim soluta dolorem in.', 679),
('23', '', 'Non sit magnam necessitatibus saepe laboriosam porro.', 1540),
('24', '', 'In omnis autem quaerat sint.', 1136),
('25', '', 'Aperiam similique sed nostrum nesciunt voluptatum similique aliquam dolorem.', 1757),
('26', '', 'Omnis tenetur consequatur adipisci qui.', 1983),
('27', '', 'Repudiandae dolore et reiciendis aliquid enim est.', 661),
('28', '', 'Facilis doloribus reiciendis beatae aut omnis beatae.', 1163),
('29', '', 'Aut repudiandae et fugiat similique saepe nam ea.', 1618),
('30', '', 'Cumque dolor molestiae et vel.', 1838),
('31', '', 'Rerum vitae est explicabo qui molestiae quam repellendus.', 1116),
('32', '', 'Corporis corrupti illum exercitationem quibusdam.', 849),
('33', '', 'Dolorum vel tenetur architecto perspiciatis natus veniam qui.', 1865),
('34', '', 'Non distinctio natus enim suscipit distinctio tenetur ratione.', 1640),
('35', '', 'Qui nihil non non illo animi.', 1183),
('36', '', 'Beatae qui tempora velit aperiam at quia recusandae consequatur.', 936),
('37', '', 'Libero modi quasi atque ea sequi blanditiis.', 1580),
('38', '', 'Voluptas tempore repellendus ut sit aliquam ut et.', 1155),
('39', '', 'Hic aperiam modi sequi et optio eos est.', 1386),
('40', '', 'Pariatur rerum aspernatur ut repellat et vero ut blanditiis.', 1413),
('41', '', 'Laborum laboriosam reiciendis exercitationem molestiae.', 600),
('42', '', 'Ullam beatae omnis et.', 1161),
('43', '', 'Dolor neque aut enim similique.', 1905),
('44', '', 'Natus quae quisquam vel ea officia sit reiciendis.', 1515),
('45', '', 'Blanditiis in ea asperiores autem doloribus rerum perferendis.', 1840),
('46', '', 'Quis nostrum aut maiores optio qui sed.', 1516),
('47', '', 'Adipisci sint ut placeat corporis asperiores.', 1124),
('48', '', 'Consequatur earum sunt impedit voluptatem similique.', 704),
('49', '', 'Et laboriosam adipisci neque harum maiores.', 941),
('50', '', 'Consequatur voluptatem numquam enim quis veniam in nulla.', 1370),
('51', '', 'Rerum quae hic occaecati voluptate eum.', 1279),
('52', '', 'Numquam quo beatae assumenda nesciunt quaerat odio.', 932),
('53', '', 'Nemo aperiam repudiandae sed cupiditate non mollitia.', 1773),
('54', '', 'Vitae consequatur quasi soluta quo minus et.', 1919),
('55', '', 'Et velit quia minus voluptatem suscipit.', 549),
('56', '', 'Laborum quae quo dolore maiores vitae voluptates hic.', 749),
('57', '', 'Quia consequatur quos fugit voluptatem.', 737),
('58', '', 'Voluptatem pariatur exercitationem distinctio quis necessitatibus ut voluptatum.', 680),
('59', '', 'Nostrum cum quaerat fugiat.', 1017),
('60', '', 'Assumenda ea facere ut delectus et.', 1062),
('61', '', 'Tempore incidunt expedita rerum dolore est assumenda temporibus.', 1728),
('62', '', 'Recusandae omnis dicta repellat suscipit id.', 1236),
('63', '', 'Velit quae beatae voluptatibus corrupti quam veniam dolor consequatur.', 1269),
('64', '', 'Inventore mollitia et rerum voluptates laboriosam.', 884),
('65', '', 'Necessitatibus perferendis asperiores ratione sunt autem eos rerum.', 1919),
('66', '', 'Natus autem voluptas necessitatibus sint molestiae.', 507),
('67', '', 'Quo molestias ut tempora nihil id.', 1884),
('68', '', 'Et voluptas sint et voluptatem.', 847),
('69', '', 'Magnam iure vel aut voluptatem sunt.', 1567),
('70', '', 'Nobis ducimus perferendis eligendi nobis enim et.', 777),
('71', '', 'Sequi praesentium quaerat quis nulla sequi nesciunt ad.', 1644),
('72', '', 'Sapiente asperiores repellat facere ex.', 933),
('73', '', 'Officiis enim rerum ut molestias maxime dolorem architecto.', 1669),
('74', '', 'Pariatur rerum eligendi occaecati dignissimos consectetur iste.', 1783),
('75', '', 'Nostrum accusamus nulla minima.', 1694),
('76', '', 'Optio veritatis maiores fugit perspiciatis.', 1406),
('77', '', 'Fuga enim autem consequatur perferendis aut ipsam optio.', 1269),
('78', '', 'Corporis odio aut natus error.', 506),
('79', '', 'Saepe suscipit nobis ex repellendus ea.', 754),
('80', '', 'Occaecati et in dolorem corporis eveniet distinctio.', 1433),
('81', '', 'Unde quis fugiat non consequatur.', 1436),
('82', '', 'Et corporis eaque explicabo eum aliquid tempora beatae provident.', 1957),
('83', '', 'Quas repellat et ut velit.', 1038),
('84', '', 'Beatae omnis et rerum nihil quisquam.', 627),
('85', '', 'Omnis praesentium voluptas aliquid aspernatur.', 1129),
('86', '', 'Blanditiis ut repellat dolor omnis hic in iusto nobis.', 1870),
('87', '', 'Voluptas sunt libero est et.', 686),
('88', '', 'Fugiat laboriosam quaerat iusto facilis et beatae.', 1150),
('89', '', 'Quisquam quisquam nostrum vero est doloribus est velit.', 875),
('90', '', 'Blanditiis et inventore sint cupiditate fugiat dolor praesentium.', 1513),
('91', '', 'Asperiores nisi doloremque a consequatur modi consequatur illum.', 1673),
('92', '', 'Praesentium repellendus sit quaerat ut.', 1906),
('93', '', 'Omnis sint iusto consequuntur sit velit magnam.', 599),
('94', '', 'Nisi inventore voluptas dolores sit architecto impedit.', 1208),
('95', '', 'Ullam officiis quis repudiandae dolorum iure.', 1936),
('96', '', 'Et dolores nam cupiditate et sed est.', 1299),
('97', '', 'Iusto omnis consequatur inventore voluptatem a earum sed ut.', 1867),
('98', '', 'Voluptatem enim dolor quod optio eum dolor.', 1499),
('99', '', 'Rem sapiente dolor nemo velit excepturi sed sequi deserunt.', 1104),
('100', '', 'Eveniet qui nobis dolores accusantium quia voluptas.', 578);


